version: "3.8"

networks:
  backend:
    driver: bridge
services:
  backend:
    build: ..
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
